### ISSUE TITLE
register_setting() got an unexpected keyword argument 'translatable'

### ISSUE THREAD

**Issue by eve1234** [stephenmcd/cartridge#253]
Hello,

I got an issue here trying to set my project up. I get the following error when trying to run - 

python manage.py createdb --noinput

or 

python manage.py runserver

python manage.py createdb --noinput
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/Django-1.6.11-py2.7.egg/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/Django-1.6.11-py2.7.egg/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Python/2.7/site-packages/Django-1.6.11-py2.7.egg/django/core/management/__init__.py", line 272, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Library/Python/2.7/site-packages/Django-1.6.11-py2.7.egg/django/core/management/__init__.py", line 75, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/Library/Python/2.7/site-packages/Django-1.6.11-py2.7.egg/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Library/Python/2.7/site-packages/Mezzanine-3.1.10-py2.7.egg/mezzanine/core/management/__init__.py", line 16, in <module>
    from mezzanine.utils.tests import copy_test_to_media
  File "/Library/Python/2.7/site-packages/Mezzanine-3.1.10-py2.7.egg/mezzanine/utils/tests.py", line 12, in <module>
    from mezzanine.conf import settings
  File "/Library/Python/2.7/site-packages/Mezzanine-3.1.10-py2.7.egg/mezzanine/conf/__init__.py", line 204, in <module>
    import_module("%s.defaults" % app)
  File "/Library/Python/2.7/site-packages/Django-1.6.11-py2.7.egg/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Library/Python/2.7/site-packages/Cartridge-0.9.5-py2.7.egg/cartridge/shop/defaults.py", line 138, in <module>
    translatable=True,
TypeError: register_setting() got an unexpected keyword argument 'translatable'

I have been looking everywhere but can't seem to find anything.  

I am able to open the defaults.py but do not what I am support to do there. Plus it's in my system settings so not advisable to edit it. Right?

Please, help.

Thanks

**Comment by stephenmcd** [comment]
You're using the development version of Cartridge which depends on the development version of Mezzanine, but you're using the released version of Mezzanine.

**Comment by eve1234** [comment]
I downloaded cartridge from here and installed using -

python setup.py install

Perhaps I should have use pip. I was getting errors with pip that's why I did the above.

What can I do to correct this?

**Comment by stephenmcd** [comment]
Do the same for Mezzanine first.

**Comment by eve1234** [comment]
which version of Mezzanine can I install for this and do I remove the already installed?

**Comment by eve1234** [comment]
I downloaded the https://github.com/stephenmcd/mezzanine and installed some way as I did the cartridge. Something seems to be working . Thank you.
